version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "nuget"
    assignees:
      - "richardsondev"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "richardsondev"
